public class Constants {

    public static final String DATABASES_UPLOAD_NOTIFICATIONS_TOPIC = "DATABASES_UPLOAD_NOTIFICATIONS";
    public static final String PIPELINES_SET_UPLOAD_NOTIFICATIONS_TOPIC_FORMAT = "PIPELINES_SET_%d_UPLOAD_NOTIFICATIONS";
    public static final String DATA_TO_PARSE_TOPIC_FORMAT = "PIPELINES_SET_%d_DATA_TO_PARSE";
    public static final String PIPELINES_SETS_UPLOAD_NOTIFICATIONS_TOPIC = "PIPELINES_SETS_UPLOAD_NOTIFICATIONS";
    public static final String PIPELINES_SETS_DONE_TOPIC = "PIPELINES_SETS_DONE";

}
